theme: minima
title: My high school 
author: @%#$
email: emcdo12@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  In this website i will write how my high school experience is.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
